# Generated by Django 5.2.5 on 2025-08-09 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('pref', models.CharField(choices=[('東京都', '東京都'), ('神奈川県', '神奈川県'), ('千葉県', '千葉県'), ('埼玉県', '埼玉県')], max_length=20)),
                ('sub_area', models.CharField(choices=[('渋谷', '渋谷'), ('新宿', '新宿'), ('原宿', '原宿'), ('高円寺', '高円寺'), ('町田', '町田'), ('浅草', '浅草'), ('みなとみらい', 'みなとみらい'), ('横浜', '横浜'), ('中山', '中山'), ('船橋', '船橋'), ('川越', '川越')], max_length=50)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
