# Generated by Django 5.2.5 on 2025-08-09 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(help_text='移動順（1から、Spot数-1まで）')),
                ('travel_minutes', models.PositiveIntegerField(default=15, help_text='移動時間(分)')),
                ('mode', models.CharField(choices=[('train', '電車'), ('bus', 'バス'), ('car', '車'), ('walk', '徒歩')], default='walk', max_length=10)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legs', to='plans.plan')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('plan', 'order')},
            },
        ),
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(help_text='訪問順（1から）')),
                ('name', models.CharField(max_length=100)),
                ('stay_minutes', models.PositiveIntegerField(default=60, help_text='滞在時間(分)')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spots', to='plans.plan')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('plan', 'order')},
            },
        ),
    ]
