# Generated by Django 5.2.5 on 2025-08-09 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_leg_spot'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='default_mode',
            field=models.CharField(choices=[('train', '電車'), ('bus', 'バス'), ('car', '車'), ('walk', '徒歩')], default='walk', max_length=10, verbose_name='デフォルト移動手段'),
        ),
    ]
