# Generated by Django 5.2.5 on 2025-08-10 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_plan_default_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='pref',
            field=models.CharField(choices=[('全国', '全国'), ('北海道', '札幌市'), ('青森県', '青森市'), ('岩手県', '盛岡市'), ('宮城県', '仙台市'), ('秋田県', '秋田市'), ('山形県', '山形市'), ('福島県', '福島市'), ('茨城県', '水戸市'), ('栃木県', '宇都宮市'), ('群馬県', '前橋市'), ('埼玉県', 'さいたま市'), ('千葉県', '千葉市'), ('東京都', '新宿区'), ('神奈川県', '横浜市'), ('新潟県', '新潟市'), ('富山県', '富山市'), ('石川県', '金沢市'), ('福井県', '福井市'), ('山梨県', '甲府市'), ('長野県', '長野市'), ('岐阜県', '岐阜市'), ('静岡県', '静岡市'), ('愛知県', '名古屋市'), ('三重県', '津市'), ('滋賀県', '大津市'), ('京都府', '京都市'), ('大阪府', '大阪市'), ('兵庫県', '神戸市'), ('奈良県', '奈良市'), ('和歌山県', '和歌山市'), ('鳥取県', '鳥取市'), ('島根県', '松江市'), ('岡山県', '岡山市'), ('広島県', '広島市'), ('山口県', '山口市'), ('徳島県', '徳島市'), ('香川県', '高松市'), ('愛媛県', '松山市'), ('高知県', '高知市'), ('福岡県', '福岡市'), ('佐賀県', '佐賀市'), ('長崎県', '長崎市'), ('熊本県', '熊本市'), ('大分県', '大分市'), ('宮崎県', '宮崎市'), ('鹿児島県', '鹿児島市'), ('沖縄県', '那覇市')], max_length=20),
        ),
        migrations.AlterField(
            model_name='plan',
            name='sub_area',
            field=models.CharField(choices=[('札幌駅', '札幌駅'), ('仙台駅', '仙台駅'), ('東京駅', '東京駅'), ('新宿駅', '新宿駅'), ('渋谷駅', '渋谷駅'), ('池袋駅', '池袋駅'), ('横浜駅', '横浜駅'), ('名古屋駅', '名古屋駅'), ('京都駅', '京都駅'), ('大阪駅', '大阪駅'), ('天王寺駅', '天王寺駅'), ('神戸駅', '神戸駅'), ('広島駅', '広島駅'), ('博多駅', '博多駅'), ('那覇空港駅', '那覇空港駅')], max_length=50),
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('name', models.CharField(max_length=100)),
                ('approx_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='plans.plan')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
