# Generated by Django 5.2.5 on 2025-08-10 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0004_spot_move_minutes_alter_plan_pref_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='move_minutes',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='移動時間(分)', null=True),
        ),
    ]
